### ISSUE TITLE
Error: parameter 'out1_mode' cannot be set because it was not declared

### ISSUE THREAD

**Issue by DanBmh** [roboception/rc_genicam_driver_ros2#2]
Hello,
I've tried to use the rcvisard in a ROS2 environment, but currently I can't start the ros node. If fails with: `parameter 'out1_mode' cannot be set because it was not declared` and restarts continuously. Do you have an idea how to fix this?

Full log:
```
ros2 run rc_genicam_driver rc_genicam_driver --ros-args -p "device:=:02912001"

[INFO] [1673350589.453600422] [genicam_driver]: Initializing
[INFO] [1673350589.453752074] [genicam_driver]: Processing thread started
[INFO] [1673350589.453788806] [genicam_driver]: Configuring
[INFO] [1673350591.686870959] [genicam_driver]: Connecting to sensor 'enp0s31f6:02912001' alias rc_visard 65c
[WARN] [1673350592.816687212] [genicam_driver]: Parameter not readable or writable: depth_smooth (DepthSmooth)
[INFO] [1673350593.713744893] [genicam_driver]: Start streaming images
[ERROR] [1673350594.363836802] [genicam_driver]: parameter 'out1_mode' cannot be set because it was not declared
[INFO] [1673350597.364177913] [genicam_driver]: Cleanup

# Keeps repeating:
[INFO] [1673350597.379570381] [genicam_driver]: Configuring
[INFO] [1673350599.471255751] [genicam_driver]: Connecting to sensor 'enp0s31f6:02912001' alias rc_visard 65c
[WARN] [1673350600.628850811] [genicam_driver]: Parameter not readable or writable: depth_smooth (DepthSmooth)
[INFO] [1673350601.524108610] [genicam_driver]: Start streaming images
[ERROR] [1673350602.173880760] [genicam_driver]: parameter 'out1_mode' cannot be set because it was not declared
```

(Installed with: `apt-get install -y --no-install-recommends ros-foxy-rc-genicam-driver`, Firmware: `22.10.0`)

**Comment by DanBmh** [comment]
Can be solved by following workaround (deletes some problematic code parts while building the docker image):
```
# Install roboception camera driver
# Fix installation of: ros-foxy-rc-genicam-driver
RUN apt-get update && apt-get install -y --no-install-recommends ros-foxy-diagnostic-updater
RUN apt-get update && apt-get install -y --no-install-recommends ros-foxy-rc-genicam-api
RUN apt-get update && apt-get install -y --no-install-recommends ros-foxy-rc-common-msgs
RUN cd /project/base/src/; git clone https://github.com/roboception/rc_genicam_driver_ros2.git --depth=1
RUN sed -i '/set_parameter(rclcpp::Parameter("out1_mode", out1_mode_on_sensor));/d' /project/base/src/rc_genicam_driver_ros2/src/genicam_driver.cpp
RUN sed -i '/string out1_mode = /d' /project/base/src/rc_genicam_driver_ros2/src/publishers/image_publisher.cpp
RUN sed -i '/bool out1 = /d' /project/base/src/rc_genicam_driver_ros2/src/publishers/image_publisher.cpp
RUN sed -i '/if (!out1 && /,+2 d' /project/base/src/rc_genicam_driver_ros2/src/publishers/image_publisher.cpp
RUN sed -i '/if (out1 && /,+2 d' /project/base/src/rc_genicam_driver_ros2/src/publishers/image_publisher.cpp
RUN sed -i '/if (!out1) /,+2 d' /project/base/src/rc_genicam_driver_ros2/src/publishers/image_publisher.cpp
RUN sed -i '/if (out1) /,+2 d' /project/base/src/rc_genicam_driver_ros2/src/publishers/image_publisher.cpp
RUN /bin/bash -i -c 'cd /project/base/; colcon build --symlink-install --packages-select rc_genicam_driver'
```

**Comment by DanBmh** [comment]
Firmware: 22.10.0
IOControl: No

**Comment by flixr** [comment]
Should be fixed, please let me know if there are still problems...

**Comment by DanBmh** [comment]
No, still not working, it now fails without a message

Log from docker-compose:
```
cam_klein_bunt_1          | [INFO] [1673444707.535984481] [cam_klein_bunt.genicam_driver]: Component 'Intensity' enabled
gesturetracker_cam_klein_bunt_1 exited with code 245
```

I already had this problem (I think it occurred as soon as the image topic was accessed) and solved it with the deletions in _image_publisher.cpp_ (comment above)

**Comment by flixr** [comment]
Sorry, missed one more thing. But that should be it now.

**Comment by DanBmh** [comment]
yes, it's working now
